# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [16]:
new_array = np.array([0,0,0,0,1,0,0,0,0,0])
new_array.reshape(2, 5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [45]:
one_d_array = np.arange(10, 50)
one_d_array = one_d_array[::-1]
one_d_array[one_d_array % 2 == 0]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [29]:
two_d_array = np.arange(0, 9).reshape((3,3))
two_d_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [65]:
x = np.random.rand(4, 3)
x.min(), x.max()

(np.float64(0.11296210814420371), np.float64(0.9075698826353028))

### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [71]:
x = np.random.rand(6, 4)
y = np.random.rand(4, 3)
x, y, x.dot(y)

(array([[0.59771917, 0.13031416, 0.9594698 , 0.43815255],
        [0.48252788, 0.38802234, 0.74472985, 0.54315106],
        [0.54150823, 0.18199843, 0.62405664, 0.08383862],
        [0.97654239, 0.08631466, 0.97456116, 0.67864364],
        [0.28122317, 0.88115368, 0.76827829, 0.74788855],
        [0.17425114, 0.80550425, 0.27124339, 0.37080101]]),
 array([[0.88541957, 0.48765322, 0.81432171],
        [0.52181868, 0.32969088, 0.92620944],
        [0.44010857, 0.6817445 , 0.37663744],
        [0.4968317 , 0.1942375 , 0.05273612]]),
 array([[1.23719157, 1.07366198, 0.99191263],
        [1.22733359, 0.97644948, 1.06145971],
        [0.89073852, 0.76580324, 0.84899499],
        [1.67577474, 1.30089095, 1.27801038],
        [1.41850355, 1.09668522, 1.37394211],
        [0.87821477, 0.60748368, 1.00967715]]))

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [77]:
x = np.random.rand(7, 7)
x.mean(), x.std()

(np.float64(0.5308804586804085), np.float64(0.2995477061133484))

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [1]:
import pandas as pd
import matplotlib as mpl
import seaborn as sb

### Загрузите датасет Tips из набора датасетов seaborn

In [4]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
tips = pd.read_csv(url)
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.